### ISSUE TITLE
10. Default Button

### ISSUE THREAD

**Issue by ClaireLagat** [Kukuza/sargo-interface#6]
# Design
![image](https://user-images.githubusercontent.com/102159494/164021313-b37bdd7b-62c6-4777-a51b-82a7da9e3b40.png)
https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=3609%3A6602

**Comment by steffenkrogmann** [comment]
@ClaireLagat 

1. Add a label "component"

2. Add sections

# Acceptance Criteria
- when user swipes.....

# Design

3. Add a link to figma.

4. Button is not called reivew button. Please check again with @Chegemartinx how specifically he approached naming things. Names should be the same everywhere.

**Comment by ClaireLagat** [comment]
@Chegemartinx I need your opinion on this.
